=== Inspiredsoft/automata/src/main/resources/inspired-fsm.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="workflow">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="state" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="transition" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="condition" minOccurs="0" maxOccurs="1"/>
                    <xs:element type="xs:string" name="action"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="to" use="required"/>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                  <xs:attribute type="xs:string" name="description" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="deactionion" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="start" use="required"/>
      <xs:attribute type="xs:string" name="itemName" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Inspiredsoft/automata/src/test/resources/purchase-order.fsm.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
/*******************************************************************************
* Inspired Automata is a framework implement a Finite State machine.
* Copyright (C) 2017 Inspired Soft
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.    
*******************************************************************************/
-->

<workflow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../main/resources/inspired-fsm.xsd"
	name="purchaseOrder" start="CREATED" itemName="order">

	<state name="CREATED" description="New order">

		<transition to="APPROVED" name="approve" description="Approve order">
			<condition>
				<![CDATA[
					return budget.value < 10;
				]]>
			</condition>
			<action>
				order.number = (int)(Math.random()*100000);
				order.approvalDate = new Date();
			</action>
		</transition>

		<transition to="DENIED" name="deny" description="Deny order">
			<condition>
				<![CDATA[
					return budget.value >= 10;
				]]>
			</condition>
			<action>
				order.note ='Order denied';
				order.cancelDate = new Date();
			</action>
		</transition>

	</state>

	<state name="APPROVED" description="Approved">

		<transition to="CANCELLED" name="cancel" description="Calcel order">
			<action>
				order.cancelDate = new Date();
			</action>
		</transition>

		<transition to="PROCESSED" name="process" description="Process order">
			<action>
				order.processDate = new Date();
				order.paid = invoice.total;
			</action>
		</transition>

	</state>

</workflow>
